#ifndef RM_SENTRY_2024_ALL_TYPE_
#define RM_SENTRY_2024_ALL_TYPE_

#include "node_library/chassis_attack_specific_enemy_node.hpp"
#include "node_library/chassis_static_attack_node.hpp"
#include "node_library/chassis_decide_speed_node.hpp"
#include "node_library/decide_enemy.hpp"
#include "node_library/defence_building_node.hpp"
#include "node_library/navigation_building_node.hpp"
#include "node_library/gimbal_choose_enemy_node.hpp"
#include "node_library/nav_to_enemy.hpp"
#include "node_library/nav_to_specific_place.hpp"
#include "node_library/patrol_1.hpp"
#include "node_library/patrol_2.hpp"
#include "node_library/patrol_3.hpp"
#include "node_library/radar_decision.hpp"
#include "node_library/spin.hpp"
#include "node_library/time_begin.hpp"
#include "node_library/time_compu_limit.hpp"
#include "node_library/time_compu_interval.hpp"
#include "node_library/nav_heal_node.hpp"
#include "node_library/lidar_attack_node.hpp"
#include "node_library/build_attack_node.hpp"
#include "node_library/nav_u_node.hpp"
#include "node_library/nav_heal_node.hpp"
#include "node_library/time_ctrl.hpp"
#include "node_library/operator_gimbal_node.hpp"
#include "node_library/operator_navigate_node.hpp"

#endif